export default function ErrorPage() {
	return (
		<>
			<title>404</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
			<h1>{"Rats! This page cannot be found. 🐀"}</h1>
		</>
	)
}
